AWSTemplateFormatVersion: "2010-09-09"
Description: "Create an AppConfig YAML Freeform Hosted Configuration Version - (v1.0.1)"
Parameters:
  # General Configuration
  InfrastructureName:
    Type: "String"
    Description: "A name used to differentiate this infrastructure from other existing infrastructure."
    Default: "main"
  ApplicationName:
    Type: "String"
    Description: "The name of the application."
  ProfileType:
    Type: "String"
    Description: "The type of configuration profile."
    AllowedValues:
    - "feature-flag"
    - "freeform"
    Default: "freeform"
  Description:
    Type: "String"
    Description: "The description of the configuration version."
  # Profile Configuration
  Author:
    Type: "String"
    Description: "The author of the website."
    Default: "Warner Bros. Discovery"
  ImageUrl:
    Type: "String"
    Description: "This is a sample image URL parameter for adding values to the profile configuration."
    Default: "https://placekitten.com/300/300" # placeholder.com and placekitten.com are free services for placeholder images.
  Title:
    Type: "String"
    Description: "Title for the site."
    Default: "AppConfig Freeform/Feature Flag Demonstration"
  Subtitle:
    Type: "String"
    Description: "Subtitle for the site."
    Default: "Welcome to the AppConfig Demonstration Site"
  SiteDescription:
    Type: "String"
    Description: "The description of the site."
    Default: "Site that demonstrates how to use AppConfig with a simple application."
  SiteType:
    Type: "String"
    Description: "The type of site."
    Default: "website"
  SiteUrl:
    Type: "String"
    Description: "The URL of the site."
    Default: "www.example.com"
  # Tag Configuration
  TagEnvironment:
    Type: "String"
    Description: "Which environment are we deploying to?"
Resources:
  AppConfigHostedConfigurationVersion:
    Type: "AWS::AppConfig::HostedConfigurationVersion"
    Properties:
      ApplicationId: !Sub "{{resolve:ssm:/appconfig/${InfrastructureName}/application/${ProfileType}/${ApplicationName}/id}}"
      ConfigurationProfileId: !Sub "{{resolve:ssm:/appconfig/${InfrastructureName}/application/${ProfileType}/${ApplicationName}/configuration-profile/${TagEnvironment}/id}}"
      Description: !Ref Description
      ContentType: "application/x-yaml" #This is the mime type that the console sets when creating YAML configurations, so sticking with it.
      Content: !Sub |
        body:
          author: "${Author}"
          description: "${SiteDescription} (${TagEnvironment})"
          image: "${ImageUrl}"
          subtitle: "${Subtitle}"
          title: "${Title}"
          type: "${SiteType}"
          url: "${SiteUrl}"
  ParamAppConfigHostedConfigurationVersionId:
    Type: "AWS::SSM::Parameter"
    Properties:
      DataType: "text"
      Description: "The AppConfig hosted configuration version ID."
      Name: !Sub "/appconfig/${InfrastructureName}/application/${ProfileType}/${ApplicationName}/configuration-version/hosted/${TagEnvironment}/id"
      Tier: "Standard"
      Type: "String"
      Value: !Ref AppConfigHostedConfigurationVersion
      Tags:
        Name: !Ref "AWS::StackName"
        application: !Ref "AWS::StackName"
        customer: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/customer}}"
        contact-email: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/contact-email}}"
        environment: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/environment}}"
        team: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/team}}"
Outputs:
  AppConfigHostedConfigurationVersion:
    Description: "The ID of the application hosted configuration version."
    Value: !Ref AppConfigHostedConfigurationVersion
    Export:
      Name: !Sub "${AWS::StackName}-AppConfigHostedConfigurationVersion"
  ParamAppConfigHostedConfigurationVersionId:
    Description: "The application hosted configuration version ID SSM parameter."
    Value: !Ref ParamAppConfigHostedConfigurationVersionId
    Export:
      Name: !Sub "${AWS::StackName}-ParamAppConfigHostedConfigurationVersionId"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: "General Configuration"
      Parameters:
      - InfrastructureName
      - ApplicationName
      - ProfileType
      - Description
    - Label:
        default: "Profile Configuration"
      Parameters:
      - Author
      - ImageUrl
      - SiteDescription
      - SiteType
      - SiteUrl
      - Title
      - Subtitle
    - Label:
        default: "Tag Configuration"
      Parameters:
      - TagEnvironment
    ParameterLabels:
      InfrastructureName:
        default: "Infrastructure Name:"
      ApplicationName:
        default: "Application Name:"
      ProfileType:
        default: "Profile Type:"
      Description:
        default: "Environment Description:"
      # Profile Configuration
      Author:
        default: "Author:"
      ImageUrl:
        default: "Image URL:"
      SiteDescription:
        default: "Site Description:"
      SiteType:
        default: "Site Type:"
      SiteUrl:
        default: "Site URL:"
      Subtitle:
        default: "Subtitle:"
      Title:
        default: "Site Title:"
      # Tag Configuration
      TagEnvironment:
        default: "Environment:"